import * as fs from "fs/promises"

import * as cc from "change-case"
import * as mm from "music-metadata"

import sanitize from "sanitize-filename";


const CONFIG = {
    port: process.env.PORT ?? 8080,
    domain: process.env.DOMAIN ?? "http://localhost:8080",
    development: (process.env.DEVELOPMENT ?? "true") != "false"
}

/**
 * @class M3uAssembler
 * @description Naively assembles an m3u file from provided metadata and file paths.
 */
class M3uAssembler {
    constructor() {
        this.metadata = {};
        this.comments = [];
        this.files = [];
    }

    /**
     * Adds a comment to the top of the file, after metadata, but before files.
     * @param {string} comment
     */
    addComment(comment) {
        if (typeof comment !== "string") return;
        this.comments.push(comment);
    }

    /**
     * Sets a global metadata entry in the .m3u file.
     * @param {string} directive
     * @param {string} data
     */
    addMetadataEntry(directive, data) {
        if (typeof directive !== "string") return;
        if (typeof data !== "string") return;
        this.metadata[directive] = data;
    }

    /**
     * Adds a file to the end of the .m3u file. Does not support per-file metadata.
     * @param {string} path
     */
    addFile(path) {
        if (typeof path !== "string") return;
        this.files.push(path);
    }

    /**
     * Assembles the info into a .m3u file string.
     * @returns {string} The .m3u file as a string.
     */
    assemble() {
        let output = "#EXTM3U\n\n";

        for (let [directive, data] of Object.entries(this.metadata)) {
            output += `#${directive}:${data}\n`;
        }

        output += "\n";

        for (let comment of this.comments) {
            output += `#${comment}\n`;
        }

        output += "\n";

        for (let file of this.files) {
            output += `${file}\n`;
        }

        return output;
    }
};

let server = Bun.serve({
    routes: {
        "/": Response.redirect("https://cataas.com/cat"),

        "/:playlist": async req => {
            let playlist = sanitize(req.params.playlist)
                    .replace(".m3u8", "")
                    .replace(".m3u", "");

            try { await fs.access(`music/${playlist}`); }
            catch { return new Response("playlist not found", { status: 404 }); }

            let assembler = new M3uAssembler();
            let artists = [];
            let albums = [];
            let genres = [];

            let metadataConfig = {
                skipCovers: true,
                skipPostHeaders: true
            };

            /** @type {Array<Promise<mm.IAudioMetadata>>} */
            let fileParsePromises = [];

            // read and add files, and read the metadata from them
            for (let file of await fs.readdir(`music/${playlist}`, { withFileTypes: true })) {
                if (!file.isFile()) continue;
                if (!Bun.file(`${file.parentPath}/${file.name}`).type.startsWith("audio/")) continue;

                assembler.addFile(`${CONFIG.domain}/${encodeURI(`${playlist}/${file.name}`)}`);

                fileParsePromises.push(
                    mm.parseFile(`${file.parentPath}/${file.name}`, metadataConfig)
                        .catch(console.warn)
                        .then(metadata => {
                            if (!metadata) return;
                            if (metadata.common.artist) artists.push(metadata.common.artist);
                            if (metadata.common.artists) artists.push(...metadata.common.artists);
                            if (metadata.common.album) albums.push(metadata.common.album);
                            if (metadata.common.genre) genres.push(...metadata.common.genre);
                        })
                );
            }

            // ...wait for all the files to be read for metadata
            await Promise.all(fileParsePromises);

            albums = [...new Set(albums)];
            artists = [...new Set(artists)];
            genres = [...new Set(genres)];

            assembler.addMetadataEntry("PLAYLIST", cc.capitalCase(playlist));
            assembler.addMetadataEntry("EXTALB", albums.length == 0 ? "Unknown" : albums.length > 4 ? "Various Albums" : albums.join(", "));
            assembler.addMetadataEntry("EXTART", artists.length == 0 ? "Unknown" : artists.length > 4 ? "Various Artists" : artists.join(", "));
            assembler.addMetadataEntry("EXTGENRE", genres.length == 0 ? "Unknown" : genres.length > 4 ? "Various Genres" : genres.join(", "));

            // apply configs after to override autogenerated ones
            let configFile = Bun.file(`music/${playlist}/config.json`);
            if (await configFile.exists()) {
                let config = await configFile.json().catch(console.warn);
                assembler.addMetadataEntry("EXTALB", config.album);
                assembler.addMetadataEntry("EXTART", config.artist);
                assembler.addMetadataEntry("EXTGENRE", config.genre);
                assembler.addMetadataEntry("EXTGRP", config.group);
            }

            assembler.addComment("Generated by web-m3u: https://github.com/undefined06855/web-m3u");

            return new Response(
                assembler.assemble(), {
                    "status": 200,
                    "headers": {
                        "Content-Type": "text/plain"
                    }
                }
            );
        },

        "/:playlist/:file": async req => {
            return new Response(Bun.file(`music/${sanitize(req.params.playlist)}/${sanitize(req.params.file)}`));
        }
    },

    port: CONFIG.port,
    development: CONFIG.development
});

console.log(`Hosting web-m3u at port ${server.port}`);
